[font.normal]
# https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.8
padding = { x = 15, y = 15 }
dynamic_padding = true
startup_mode = "Maximized"
dynamic_title = false

[colors]
draw_bold_text_with_bright_colors = true

# hack for windows because control+space is eaten by alacritty.
# see: https://github.com/alacritty/alacritty/issues/1703#issuecomment-2682717776
[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"
