[font]
# starting zoomed in helps on the eyes..
size = 25
# use a nerd font that has ligatures!
# see: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono
normal = { family = "JetBrainsMono Nerd Font" }
# increase horizontal letter spacing just a bit to get that sweet spot on the eyes
offset = { x = 1 }

[window]
# avoid having to maximize the window after starting
startup_mode = "Maximized"
# can be nice to see whats behind the terminal
opacity = 0.8
padding = { x = 15, y = 15 }
dynamic_padding = true
dynamic_title = false

[colors]
# bright colors help on the eyes..
draw_bold_text_with_bright_colors = true

# hack for windows because control+space is eaten by alacritty.
# see: https://github.com/alacritty/alacritty/issues/1703#issuecomment-2682717776
[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"
